FROM fedora:latest

WORKDIR /tmp

RUN dnf -y upgrade && dnf -y install \
    git \
    cmake gcc-c++ zlib-devel \
    cfitsio-devel libnova-devel libusb1-devel libcurl-devel \
    gsl-devel libjpeg-devel fftw-devel rtl-sdr-devel libev-devel \
    qt5-qtbase-devel

RUN git clone https://github.com/google/googletest.git googletest && \
    cd googletest && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON . && \
    make && \
    make install && \
    rm -rf /tmp/googletest
