name: Docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: fedora-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["fedora"]

    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./.github/docker/Dockerfile.${{ matrix.container }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
